//Source Code -

/*

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chai aur Code - Video 32</title>
</head>
<body>
       <ul class="unordered-list">
            <li id="id1" class="list-item1">One</li>
            <li id="id2" class="list-item1">Two</li>
            <li id="id3" class="list-item1">Thre
        </ul>
        <ul class="unordered-list"> 
            <li class="list-item" name="Name1">One</li>
            <li class="list-item" name="Name1">Two</li>
            <li class="list-item" name="Name1">Three</li>
    </div>
</body>
</html>

*/

/*

NOTE - The example below is based on the selection of only one element. If there are 2 or more than that
same elements then the .querySelector will select only the first element. 

=============================================================================================================
HTMLCollection
=============================================================================================================
1. In HTML collection we get only those elements which we have selected and not all the sub elements inside it.
2. They are live collection. Whatever change we make in the DOM, it gets updated in the HTML collection immediately.
3. It select only class names, tag names.
4. They are access by using index, .namedItem() for Id & name attributes.
5. forEach() not work.
6. It was generated by .getElementByClassName(), .getElementByTagName().

Code - 
    let getById = document.getElementsByClassName('unordered-list')
    console.log(getById)

Output -
    HTMLCollection(2) [ul.unordered-list, ul.unordered-list]
    0: ul.unordered-list
    : ul.unordered-list
    length: 2
    [[Prototype]]: HTMLCollection

=============================================================================================================
NodeList
=============================================================================================================
1. Node lists can hold text, tags, attributes, comments, and more not like HTMLCollection.
2. They are static collection except NodeList created by .getElementByName (live collection)
3. They are access only by index values. intially index was start from 0.
4. forEach() successfully used.
5. It was generated by .querySelectorAll()

*/

/* 

=============================================================================================================
Creating NodeList & HTML Collection for .querySelector()
=============================================================================================================

let querySelectAll = document.querySelector('ul')
console.log(querySelectAll.children) -> for HTMLCollection
console.log(querySelectAll.childNodes) -> for NodeList

1 HTMLCollection(3) [li#id1.list-item1, li#id2.list-item1, li#id3.list-item1, id1: li#id1.list-item1, id2: li#id2.list-item1, id3: li#id3.list-item1]
2 NodeList(7) [text, li#id1.list-item1, text, li#id2.list-item1, text, li#id3.list-item1, text]

*/
